version: 2.1 # use CircleCI 2.1
jobs: # a collection of steps
    build: # runs not using Workflows must have a `build` job as entry point
        working_directory: ~/tcup-server # directory where steps will run
        docker: # run the steps with Docker
            - image: circleci/node # ...with this image as the primary container; this is where all `steps` will run
            - image: circleci/mongo
        steps: # a collection of executable commands
            - checkout # special step to check out source code to working directory
            - run:
                  name: install-yarn
                  command: 'sudo npm install -g yarn@latest'
            - restore_cache: # special step to restore the dependency cache
                  # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
                  key: dependency-cache-{{ checksum "yarn.lock" }}
            - run:
                  name: yarn-install
                  command: yarn install
            - save_cache: # special step to save the dependency cache
                  key: dependency-cache-{{ checksum "yarn.lock" }}
                  paths:
                      - ./node_modules
            - run: # run tests
                  name: test
                  command: yarn test
                  environment:
                      - NODE_ENV: test
                      - MONGO_URI_TEST: mongodb://localhost:27017/tcup_test
                      - JWT_SECRET: myjwtsecretforencryption

            - run:
                  name: make-code-coverage-dir
                  command: mkdir .nyc_output
            - run: # run coverage report
                  name: code-coverage
                  command: 'yarn coverage'
