name: deploy-new-development

on:
    push:
        branches:
            - new/development

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]
                mongodb-version: ['4.4']

        steps:
            - name: Git checkout
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - run: yarn install --frozen-lockfile
            - run: yarn lint
            - run: yarn format:check

            - name: audit
              run: yarn audit --level high --groups dependencies

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: tcup-api-new
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
                  usedocker: true
