name: deploy-production

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]
                mongodb-version: ['4.4']

        steps:
            - name: Git checkout
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.7.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}

            - run: yarn install
            - run: yarn lint
            - run: yarn format:check

            - run: yarn test
              env:
                  MONGO_URI_TEST: mongodb://localhost:27017/tcup_test
                  JWT_SECRET: some_jwt_secret

            - name: audit
              run: yarn audit --level high --groups dependencies

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: tcup-2022-api
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
